name: "Apply_TF_Plan"
on:

  push:
    branches: [ "feature/changes" ]

permissions:
  contents:
    read

jobs:
  apply-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -var github_token="${{ secrets.GIT_TOKEN }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -var github_token="${{ secrets.GIT_TOKEN }}"
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -var github_token="${{ secrets.GIT_TOKEN }}"
